### ISSUE TITLE
レスポンシブ対応

### ISSUE THREAD

**Issue by 0ctan** [sfc-icar/sfc-icar.github.io#7]
My iPhone7で表示したときに右側がガバガバに余る
レイアウトはスマホっぽい画面になっているが、ガバガバ
詰めが甘い(ブーメラン

**Comment by feles-ao42** [comment]
CSSはいじってないので、おそらく前からです…
CSSってどうやってつくったか覚えていらっしゃいますか…？
解決策が思いつき次第直します。

**Comment by 0ctan** [comment]
たぶんコピペ
